spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/group_finance
    username: postgres
    password: 2006
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
